#!/bin/bash
#
# 5-telemetry_deploy.sh
#
# Deploys the auditd telemetry layer on hawthorne-app-01, runs a controlled
# test sequence, and verifies every authorized test action left the
# expected trace in the expected log -- a hardened system that produces no
# evidence is a silent system. This script proves the evidence pipeline
# actually works, not just that it's configured.
#
# Usage:
#   sudo ./5-telemetry_deploy.sh [capstone_dir]
#
# Exit codes:
#   0 - every test action produced its expected auditd record
#   1 - deployment completed but at least one test action was not covered
#   2 - environment error (missing rules file, missing tools, cannot
#       activate auditd, cannot write output)
#
set -uo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
CAPSTONE_DIR="${1:-$SCRIPT_DIR/capstone}"
TELEMETRY_DIR="$CAPSTONE_DIR/telemetry"
# Writes: capstone/telemetry/linux_events.json and capstone/telemetry/linux_coverage.json
EVENTS_JSON="$TELEMETRY_DIR/linux_events.json"
COVERAGE_JSON="$TELEMETRY_DIR/linux_coverage.json"

# Project-provided rules file -- shipped, not generated by this script.
RULES_FILE="${RULES_FILE:-/etc/audit/rules.d/meddefense.rules}"
AUDIT_LOG="${AUDIT_LOG:-/var/log/audit/audit.log}"
SYSLOG_FILE="${SYSLOG_FILE:-/var/log/syslog}"
AUTHLOG_FILE="${AUTHLOG_FILE:-/var/log/auth.log}"

die() { printf '[telemetry] ERROR: %s\n' "$1" >&2; case "${2:-2}" in 1) exit 1 ;; *) exit 2 ;; esac; }
log() { printf '[telemetry] %s\n' "$*" >&2; }

# ---------------------------------------------------------------------------
# Preconditions
# ---------------------------------------------------------------------------
[[ "${EUID:-$(id -u)}" -eq 0 ]] || die "this script must be run as root (sudo ./5-telemetry_deploy.sh)"

for cmd in jq hostname date auditctl ausearch; do
  command -v "$cmd" >/dev/null 2>&1 || die "required command not found: $cmd"
done

[[ -f "$RULES_FILE" ]] || die "auditd rules file not found: $RULES_FILE (shipped with the project, this script does not create it)"

mkdir -p "$TELEMETRY_DIR" || die "failed to create $TELEMETRY_DIR"
[[ -w "$TELEMETRY_DIR" ]] || die "$TELEMETRY_DIR is not writable"

# ---------------------------------------------------------------------------
# 1. Ensure auditd is active with the project-provided rules file loaded.
# Tries systemctl first (the correct path on the real Hawthorne server);
# falls back to a direct binary check for environments without a running
# init system (e.g. containers), so this script is testable everywhere.
# ---------------------------------------------------------------------------
log "Ensuring auditd is active with $RULES_FILE loaded..."

AUDITD_ACTIVE=0
if command -v systemctl >/dev/null 2>&1 && systemctl is-active --quiet auditd 2>/dev/null; then
  AUDITD_ACTIVE=1
elif pgrep -x auditd >/dev/null 2>&1; then
  AUDITD_ACTIVE=1
fi

if [[ "$AUDITD_ACTIVE" -eq 0 ]]; then
  if command -v systemctl >/dev/null 2>&1 && systemctl enable --now auditd >/dev/null 2>&1; then
    AUDITD_ACTIVE=1
  else
    # No systemd available -- start the daemon directly (sandbox/container fallback).
    nohup auditd -n >/tmp/auditd_5telemetry.log 2>&1 &
    sleep 2
    pgrep -x auditd >/dev/null 2>&1 && AUDITD_ACTIVE=1
  fi
fi
[[ "$AUDITD_ACTIVE" -eq 1 ]] || die "could not bring auditd to an active state"

if command -v augenrules >/dev/null 2>&1; then
  augenrules --load >/dev/null 2>&1 || auditctl -R "$RULES_FILE" >/dev/null 2>&1
else
  auditctl -R "$RULES_FILE" >/dev/null 2>&1
fi
RULE_COUNT="$(auditctl -l 2>/dev/null | grep -c .)"
[[ "$RULE_COUNT" -gt 0 ]] || die "auditd is active but no rules are loaded from $RULES_FILE"
log "auditd active, $RULE_COUNT rule(s) loaded"

# ---------------------------------------------------------------------------
# Helper: search for a key's records added since a given line-count marker
# in $AUDIT_LOG. This deliberately does NOT use ausearch's -ts flag: it was
# found to return zero results unconditionally in testing (confirmed with
# ausearch 3.1.2, independent of locale, with or without -if) -- likely an
# environment-specific auparse quirk, not something safe to depend on. A
# line-count marker captured immediately before the test sequence achieves
# the same goal (never report a stale hit from a previous run) without
# depending on ausearch's date parsing, and without the more invasive
# alternative of restarting auditd to get a fresh log file.
# ---------------------------------------------------------------------------
capture_log_marker() { wc -l < "$AUDIT_LOG" 2>/dev/null || echo 0; }

search_key_since() {
  local key="$1" marker="$2"
  tail -n "+$((marker + 1))" "$AUDIT_LOG" 2>/dev/null | grep -c "key=\"$key\"" || true
}

# ---------------------------------------------------------------------------
# 2 & 3. Run the controlled test sequence; verify each action's expected
# auditd record by key search.
# ---------------------------------------------------------------------------
COVERAGE_ACTIONS="[]"
ALL_COVERED=1

record_action() {
  local action="$1" key="$2" cmd_used="$3" hits="$4"
  local found=false
  [[ "$hits" -gt 0 ]] && found=true
  [[ "$found" == "true" ]] || ALL_COVERED=0

  local entry
  entry="$(jq -n \
    --arg action "$action" \
    --arg search_key "$key" \
    --arg command_used "$cmd_used" \
    --argjson found "$found" \
    --argjson evidence_count "$hits" \
    --arg checked_at "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    '{action: $action, search_key: $search_key, command_used: $command_used, expected: true, found: $found, evidence_count: $evidence_count, checked_at: $checked_at}')"
  COVERAGE_ACTIONS="$(jq --argjson e "$entry" '. + [$e]' <<< "$COVERAGE_ACTIONS")"
  log "action '$action' key=$key evidence_count=$hits found=$found"
}

TEST_USER="meddefense_telemetry_test"

log "Running controlled test sequence..."
LOG_MARKER="$(capture_log_marker)"

# Action 1: create a user
userdel -f "$TEST_USER" >/dev/null 2>&1 || true
useradd -M -N "$TEST_USER" >/dev/null 2>&1
sleep 1
record_action "create_user" "meddefense-user-mgmt" "useradd -M -N $TEST_USER" "$(search_key_since meddefense-user-mgmt "$LOG_MARKER")"

# Action 2: remove the user
userdel -f "$TEST_USER" >/dev/null 2>&1
sleep 1
record_action "remove_user" "meddefense-user-mgmt" "userdel -f $TEST_USER" "$(search_key_since meddefense-user-mgmt "$LOG_MARKER")"

# Action 3: service management action (read-only status check -- safe, reversible)
if command -v systemctl >/dev/null 2>&1; then
  systemctl status cron >/dev/null 2>&1 || true
else
  service cron status >/dev/null 2>&1 || true
fi
sleep 1
record_action "service_management" "meddefense-service-mgmt" "systemctl status cron" "$(search_key_since meddefense-service-mgmt "$LOG_MARKER")"

# Action 4: schedule a cron job
CRON_TEST_FILE="/etc/cron.d/meddefense-telemetry-test"
echo "* * * * * root /bin/true" > "$CRON_TEST_FILE"
sleep 1
record_action "schedule_cron" "meddefense-cron" "write $CRON_TEST_FILE" "$(search_key_since meddefense-cron "$LOG_MARKER")"

# Action 5: remove the cron job
rm -f "$CRON_TEST_FILE"
sleep 1
record_action "remove_cron" "meddefense-cron" "rm $CRON_TEST_FILE" "$(search_key_since meddefense-cron "$LOG_MARKER")"

# Action 6: short authorized find as root
find /tmp -maxdepth 1 -name "meddefense-telemetry-marker" >/dev/null 2>&1
sleep 1
record_action "authorized_find" "meddefense-recon-find" "find /tmp -maxdepth 1 -name meddefense-telemetry-marker" "$(search_key_since meddefense-recon-find "$LOG_MARKER")"

# ---------------------------------------------------------------------------
# Write linux_coverage.json (per-action schema shared with the Windows
# sibling -- see 5-telemetry_deploy.ps1's windows_coverage.json).
# ---------------------------------------------------------------------------
PASSED_COUNT="$(jq '[.[] | select(.found)] | length' <<< "$COVERAGE_ACTIONS")"
TOTAL_COUNT="$(jq 'length' <<< "$COVERAGE_ACTIONS")"
FAILED_COUNT="$((TOTAL_COUNT - PASSED_COUNT))"

jq -n \
  --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  --arg hostname "$(hostname)" \
  --argjson actions "$COVERAGE_ACTIONS" \
  --argjson total_actions "$TOTAL_COUNT" \
  --argjson passed_count "$PASSED_COUNT" \
  --argjson failed_count "$FAILED_COUNT" \
  --argjson all_passed "$([[ $ALL_COVERED -eq 1 ]] && echo true || echo false)" \
  '{
    timestamp: $timestamp,
    hostname: $hostname,
    actions: $actions,
    total_actions: $total_actions,
    passed_count: $passed_count,
    failed_count: $failed_count,
    all_passed: $all_passed
  }' > "$COVERAGE_JSON" || die "failed to write $COVERAGE_JSON"
log "Wrote $COVERAGE_JSON"

# ---------------------------------------------------------------------------
# 4. Export the last 30 minutes of auditd + syslog records as structured
# JSON, matching the field-name/envelope convention already established
# by the 2x02 telemetry handoff (metadata + events[], each event with
# timestamp/hostname/platform/source_type/event_category/raw_message).
# ---------------------------------------------------------------------------
log "Exporting last 30 minutes of auditd + syslog records..."

HOSTNAME_VAL="$(hostname)"
NOW_ISO="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
CUTOFF_EPOCH="$(( $(date +%s) - 1800 ))"

# Read the raw audit.log directly and filter by the epoch embedded in each
# record's own msg=audit(EPOCH.MS:SERIAL) field. This deliberately avoids
# ausearch's -ts flag -- confirmed non-functional in this environment (see
# the note on search_key_since above) -- in favor of parsing the log's own
# authoritative timestamp, which needs no external date-parsing at all.
AUDIT_EVENTS_JSON="$(
  if [[ -r "$AUDIT_LOG" ]]; then
    awk -v cutoff="$CUTOFF_EPOCH" '
      function extract(str, re,    saved_start, saved_len, result) {
        saved_start = RSTART; saved_len = RLENGTH
        if (match(str, re)) {
          result = substr(str, RSTART, RLENGTH)
        } else {
          result = ""
        }
        RSTART = saved_start; RLENGTH = saved_len
        return result
      }
      {
        epoch_field = extract($0, "msg=audit\\([0-9]+\\.")
        if (epoch_field == "") next
        gsub(/msg=audit\(/, "", epoch_field); gsub(/\./, "", epoch_field)
        epoch = epoch_field + 0
        if (epoch < cutoff) next

        type_field = extract($0, "^type=[A-Z_]+")
        gsub(/^type=/, "", type_field)
        if (type_field == "") type_field = "unknown"

        key_field = extract($0, "key=\"[^\"]*\"")
        gsub(/^key="/, "", key_field); gsub(/"$/, "", key_field)

        comm_field = extract($0, "comm=\"[^\"]*\"")
        gsub(/^comm="/, "", comm_field); gsub(/"$/, "", comm_field)

        printf "%s\t%s\t%s\t%s\n", epoch, type_field, key_field, comm_field
      }
    ' "$AUDIT_LOG" 2>/dev/null | tail -2000
  fi | jq -R -s '
    split("\n") | map(select(length > 0)) | map(split("\t")) | map({
      epoch: (.[0] | tonumber? // 0),
      type: .[1], key: (.[2] // ""), comm: (.[3] // "")
    })
  '
)"
[[ -n "$AUDIT_EVENTS_JSON" && "$AUDIT_EVENTS_JSON" != "null" ]] || AUDIT_EVENTS_JSON="[]"

AUDIT_EVENTS_JSON="$(jq --arg hostname "$HOSTNAME_VAL" '
  map({
    timestamp: (.epoch | strftime("%Y-%m-%dT%H:%M:%SZ")),
    hostname: $hostname,
    platform: "Linux",
    source_type: "auditd",
    event_category: .type,
    raw_message: ("type=" + .type + (if (.key | length) > 0 then (" key=" + .key) else "" end) + (if (.comm | length) > 0 then (" comm=" + .comm) else "" end))
  })
' <<< "$AUDIT_EVENTS_JSON")"

collect_syslog_events() {
  local file="$1" source_type="$2"
  [[ -r "$file" ]] || { echo "[]"; return; }
  awk -v cutoff="$(date -u -d '-30 minutes' +%Y-%m-%dT%H:%M:%S 2>/dev/null || date -u -v-30M +%Y-%m-%dT%H:%M:%S)" '
    { ts=$1; if (substr(ts,1,19) >= cutoff) print }
  ' "$file" 2>/dev/null | tail -500 | jq -R -s --arg hostname "$HOSTNAME_VAL" --arg source_type "$source_type" '
    split("\n") | map(select(length > 0)) | map(
      capture("^(?<ts>\\S+)\\s+(?<host>\\S+)\\s+(?<rest>.*)$") as $m
      | {
          timestamp: ($m.ts // ""),
          hostname: $hostname,
          platform: "Linux",
          source_type: $source_type,
          event_category: "system",
          raw_message: ($m.rest // .)
        }
    )
  '
}

SYSLOG_EVENTS_JSON="$(collect_syslog_events "$SYSLOG_FILE" "syslog")"
AUTHLOG_EVENTS_JSON="$(collect_syslog_events "$AUTHLOG_FILE" "auth.log")"
[[ -n "$SYSLOG_EVENTS_JSON" && "$SYSLOG_EVENTS_JSON" != "null" ]] || SYSLOG_EVENTS_JSON="[]"
[[ -n "$AUTHLOG_EVENTS_JSON" && "$AUTHLOG_EVENTS_JSON" != "null" ]] || AUTHLOG_EVENTS_JSON="[]"

EVENTS_TMPFILE="$(mktemp)"
jq -s 'add' <<< "$AUDIT_EVENTS_JSON"$'\n'"$SYSLOG_EVENTS_JSON"$'\n'"$AUTHLOG_EVENTS_JSON" > "$EVENTS_TMPFILE"

# --slurpfile (reads from a file) instead of --argjson (a command-line
# argument) -- the combined events array can be large enough to exceed
# the OS argv size limit ("Argument list too long") if passed inline.
jq -n \
  --arg generated_at "$NOW_ISO" \
  --arg hostname "$HOSTNAME_VAL" \
  --slurpfile events_wrapper "$EVENTS_TMPFILE" \
  '{
    metadata: {
      generated_at: $generated_at,
      hostname: $hostname,
      platform: "Linux",
      time_window_hours: 0.5,
      normalized_to_utc: true,
      normalized_at_utc: $generated_at
    },
    events: $events_wrapper[0]
  }' > "$EVENTS_JSON" || die "failed to write $EVENTS_JSON"
rm -f "$EVENTS_TMPFILE"

log "Wrote $EVENTS_JSON ($(jq '.events | length' "$EVENTS_JSON") events)"

# ---------------------------------------------------------------------------
# Verdict
# ---------------------------------------------------------------------------
if [[ "$ALL_COVERED" -eq 1 ]]; then
  log "PASS: all $TOTAL_COUNT test actions produced their expected auditd record"
  exit 0
else
  log "FAIL: $FAILED_COUNT of $TOTAL_COUNT test action(s) did not produce the expected record"
  exit 1
fi