#!/bin/bash
#
# 6-patch_pipeline.sh
#
# Deploys the patch management pipeline on hawthorne-app-01. This script
# does not reinvent the pipeline -- it wraps the existing pipeline script
# from the 2x03 project with client-specific directory redirection, points
# it at the capstone-provided CVE feed, configures unattended-upgrades
# with the mandated blacklist, and emits a summary of every artifact the
# pipeline produced.
#
# IMPORTANT: PIPELINE_SCRIPT defaults to this repo's test fixture
# (test_fixtures/patch_pipeline/patch_pipeline.sh), used to validate this
# wrapper end-to-end. Before running against the real Hawthorne server,
# override it with the actual pipeline script from the 2x03 project:
#   PIPELINE_SCRIPT=/path/to/real/patch_pipeline.sh ./6-patch_pipeline.sh
#
# Usage:
#   sudo ./6-patch_pipeline.sh [capstone_dir]
#
# Exit codes:
#   0 - the underlying pipeline exited 0 AND failed_entries == 0
#   1 - the pipeline ran but failed_entries > 0 (or exited non-zero)
#   2 - environment error (missing CVE feed / blacklist, cannot configure
#       unattended-upgrades, cannot write output)
#
set -uo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
CAPSTONE_DIR="${1:-$SCRIPT_DIR/capstone}"
# Writes: capstone/patch/{vulnerability_inventory.json,patch_plan.json,patch_execution_log.json}
ARTIFACTS_DIR="$CAPSTONE_DIR/patch"
SUMMARY_JSON="$CAPSTONE_DIR/patch_summary.json"

PIPELINE_SCRIPT="${PIPELINE_SCRIPT:-$SCRIPT_DIR/test_fixtures/patch_pipeline/patch_pipeline.sh}"
CVE_FEED_PATH="${CVE_FEED_PATH:-/home/analyst/MedDefense_Lab/capstone/cve_feed.json}"
BLACKLIST_JSON_PATH="${BLACKLIST_JSON_PATH:-/home/analyst/MedDefense_Lab/capstone/blacklist.json}"
UNATTENDED_UPGRADES_CONF="${UNATTENDED_UPGRADES_CONF:-/etc/apt/apt.conf.d/50unattended-upgrades}"

die() { printf '[patch] ERROR: %s\n' "$1" >&2; case "${2:-2}" in 1) exit 1 ;; *) exit 2 ;; esac; }
log() { printf '[patch] %s\n' "$*" >&2; }

# ---------------------------------------------------------------------------
# Preconditions
# ---------------------------------------------------------------------------
[[ "${EUID:-$(id -u)}" -eq 0 ]] || die "this script must be run as root (sudo ./6-patch_pipeline.sh)"

for cmd in jq hostname date apt-get; do
  command -v "$cmd" >/dev/null 2>&1 || die "required command not found: $cmd"
done

[[ -f "$PIPELINE_SCRIPT" ]] || die "pipeline script not found: $PIPELINE_SCRIPT"
[[ -x "$PIPELINE_SCRIPT" ]] || die "pipeline script is not executable: $PIPELINE_SCRIPT"
[[ -f "$CVE_FEED_PATH" ]] || die "CVE feed not found: $CVE_FEED_PATH (shipped with the project, this script does not create it)"
jq empty "$CVE_FEED_PATH" 2>/dev/null || die "CVE feed at $CVE_FEED_PATH is corrupted (invalid JSON)"
[[ -f "$BLACKLIST_JSON_PATH" ]] || die "blacklist not found: $BLACKLIST_JSON_PATH (shipped with the project, this script does not create it)"
jq empty "$BLACKLIST_JSON_PATH" 2>/dev/null || die "blacklist at $BLACKLIST_JSON_PATH is corrupted (invalid JSON)"

mkdir -p "$ARTIFACTS_DIR" || die "failed to create $ARTIFACTS_DIR"
[[ -w "$ARTIFACTS_DIR" ]] || die "$ARTIFACTS_DIR is not writable"

# ---------------------------------------------------------------------------
# 3. Configure unattended-upgrades with the mandated blacklist. Rendered
# deterministically each run (idempotent) from blacklist.json's own
# "blacklist" array -- this file's content is the source of truth, this
# script only projects it into apt's expected config syntax.
# ---------------------------------------------------------------------------
log "Configuring unattended-upgrades blacklist from $BLACKLIST_JSON_PATH..."

BLACKLIST_ENTRIES="$(jq -r '.blacklist[]?' "$BLACKLIST_JSON_PATH")"
if [[ -z "$BLACKLIST_ENTRIES" ]]; then
  die "blacklist.json has no entries under .blacklist"
fi

{
  echo "// Generated by 6-patch_pipeline.sh from $BLACKLIST_JSON_PATH -- do not edit by hand."
  echo "Unattended-Upgrade::Package-Blacklist {"
  while IFS= read -r pkg; do
    [[ -z "$pkg" ]] && continue
    printf '    "%s";\n' "$pkg"
  done <<< "$BLACKLIST_ENTRIES"
  echo "};"
} > "$UNATTENDED_UPGRADES_CONF" || die "failed to write $UNATTENDED_UPGRADES_CONF"
log "Wrote $UNATTENDED_UPGRADES_CONF"

# ---------------------------------------------------------------------------
# 1 & 2. Invoke the pipeline with CAPSTONE_ARTIFACTS_DIR set so every
# sub-step artifact lands inside the capstone package, pointed at the
# capstone-provided CVE feed.
# ---------------------------------------------------------------------------
log "Invoking pipeline: $PIPELINE_SCRIPT"
PIPELINE_LOG="$(mktemp)"

CAPSTONE_ARTIFACTS_DIR="$ARTIFACTS_DIR" CVE_FEED_PATH="$CVE_FEED_PATH" \
  "$PIPELINE_SCRIPT" > "$PIPELINE_LOG" 2>&1
PIPELINE_EXIT_CODE=$?

cat "$PIPELINE_LOG" >&2
log "pipeline exited with code $PIPELINE_EXIT_CODE"

# ---------------------------------------------------------------------------
# 4. Capture every sub-step artifact path by listing the redirected
# artifacts directory -- this makes no assumption about the pipeline's
# internal structure or output conventions, so it works with any real
# pipeline implementation, not just the test fixture.
# ---------------------------------------------------------------------------
ARTIFACT_PATHS_JSON="$(find "$ARTIFACTS_DIR" -type f 2>/dev/null | sort | jq -R -s 'split("\n") | map(select(length > 0))')"
[[ -n "$ARTIFACT_PATHS_JSON" && "$ARTIFACT_PATHS_JSON" != "null" ]] || ARTIFACT_PATHS_JSON="[]"
ARTIFACT_COUNT="$(jq 'length' <<< "$ARTIFACT_PATHS_JSON")"
log "discovered $ARTIFACT_COUNT artifact(s) under $ARTIFACTS_DIR"

EXEC_LOG_JSON="$ARTIFACTS_DIR/patch_execution_log.json"
FAILED_ENTRIES=""
if [[ -f "$EXEC_LOG_JSON" ]] && jq empty "$EXEC_LOG_JSON" 2>/dev/null; then
  FAILED_ENTRIES="$(jq -r '.failed_entries // (.entries // [] | map(select(.state == "failed")) | length)' "$EXEC_LOG_JSON")"
fi
if [[ -z "$FAILED_ENTRIES" || "$FAILED_ENTRIES" == "null" ]]; then
  log "WARNING: could not determine failed_entries from $EXEC_LOG_JSON (missing or invalid); treating as failed"
  FAILED_ENTRIES=-1
fi

# ---------------------------------------------------------------------------
# Emit the summary
# ---------------------------------------------------------------------------
TIMESTAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
HOSTNAME_VAL="$(hostname)"
PASS="$([[ "$PIPELINE_EXIT_CODE" -eq 0 && "$FAILED_ENTRIES" -eq 0 ]] && echo true || echo false)"

jq -n \
  --arg timestamp "$TIMESTAMP" \
  --arg hostname "$HOSTNAME_VAL" \
  --arg pipeline_script "$PIPELINE_SCRIPT" \
  --arg cve_feed_path "$CVE_FEED_PATH" \
  --arg blacklist_path "$BLACKLIST_JSON_PATH" \
  --argjson pipeline_exit_code "$PIPELINE_EXIT_CODE" \
  --argjson failed_entries "$FAILED_ENTRIES" \
  --argjson artifact_paths "$ARTIFACT_PATHS_JSON" \
  --argjson pass "$PASS" \
  '{
    timestamp: $timestamp,
    hostname: $hostname,
    pipeline_script: $pipeline_script,
    cve_feed_path: $cve_feed_path,
    blacklist_path: $blacklist_path,
    pipeline_exit_code: $pipeline_exit_code,
    failed_entries: $failed_entries,
    artifact_paths: $artifact_paths,
    pass: $pass
  }' > "$SUMMARY_JSON" || die "failed to write $SUMMARY_JSON"

rm -f "$PIPELINE_LOG"
log "Wrote $SUMMARY_JSON"

# ---------------------------------------------------------------------------
# 5. Verdict
# ---------------------------------------------------------------------------
if [[ "$PASS" == "true" ]]; then
  log "PASS: pipeline exit code 0, failed_entries 0"
  exit 0
else
  log "FAIL: pipeline_exit_code=$PIPELINE_EXIT_CODE failed_entries=$FAILED_ENTRIES"
  exit 1
fi