#!/bin/bash
#
# 13-dns_filtering.sh
#
# Configures dnsmasq as a local DNS sinkhole for known-malicious domains,
# leaving legitimate resolution untouched, and validates both paths with
# real `dig @127.0.0.1` queries.
#
# DNS is the quietest channel on the network -- almost never blocked, almost
# never inspected. The long TXT-record tunneling query task 9 flagged is
# exactly the kind of traffic this filter cuts off at the source.
#
# This script does NOT touch /etc/resolv.conf. It only configures dnsmasq
# on the loopback interface; routing real traffic through it is a separate
# deployment decision outside this project's scope.
#
# Usage:
#   sudo ./13-dns_filtering.sh
#
set -uo pipefail

BLOCKLIST="${BLOCKLIST:-/home/analyst/MedDefense_Lab/dns/blocklist.txt}"
ALLOWLIST="${ALLOWLIST:-/home/analyst/MedDefense_Lab/dns/allowlist.txt}"
UPSTREAM_CONF="${UPSTREAM_CONF:-/etc/dnsmasq.d/meddefense-upstream.conf}"
BLOCKLIST_CONF="${BLOCKLIST_CONF:-/etc/dnsmasq.d/meddefense-blocklist.conf}"
LOGGING_CONF="${LOGGING_CONF:-/etc/dnsmasq.d/meddefense-logging.conf}"
LOG_FILE="${LOG_FILE:-/var/log/dnsmasq.log}"
UNLISTED_DOMAIN="${UNLISTED_DOMAIN:-ubuntu.com}"
SINKHOLE_IP="0.0.0.0"

die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

[[ "${EUID:-$(id -u)}" -eq 0 ]] || die "this script must be run as root (sudo ./13-dns_filtering.sh)"

# ---------------------------------------------------------------------------
# 1. Install dnsmasq if missing (idempotent)
# ---------------------------------------------------------------------------
echo -n "[*] Ensuring dnsmasq is installed..."
if ! command -v dnsmasq >/dev/null 2>&1; then
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y dnsmasq >/dev/null
fi
command -v dnsmasq >/dev/null 2>&1 || die "dnsmasq installation failed"
DNSMASQ_VERSION="$(dnsmasq --version 2>&1 | head -1 | awk '{print $1, $3}')"
printf '     %s\n' "$DNSMASQ_VERSION"

command -v dig >/dev/null 2>&1 || die "dig (dnsutils/bind9-dnsutils) is required for validation"

# ---------------------------------------------------------------------------
# Preconditions on the inputs this script depends on but does not own
# ---------------------------------------------------------------------------
[[ -f "$BLOCKLIST" ]] || die "blocklist not found: $BLOCKLIST"
[[ -f "$ALLOWLIST" ]] || die "allowlist not found: $ALLOWLIST"
[[ -f "$UPSTREAM_CONF" ]] || die "upstream config not found: $UPSTREAM_CONF (shipped with the project, this script does not create it)"

# ---------------------------------------------------------------------------
# 2 & 3a. Read the blocklist and render meddefense-blocklist.conf
#         (address=/domain/0.0.0.0 per entry; blank lines and # comments skipped)
# ---------------------------------------------------------------------------
echo -n "[*] Rendering blocklist..."
{
  echo "# Generated by 13-dns_filtering.sh from $BLOCKLIST -- do not edit by hand."
  DOMAIN_COUNT=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    domain="$(echo "$line" | sed 's/#.*$//' | tr -d '[:space:]')"
    [[ -z "$domain" ]] && continue
    echo "address=/${domain}/${SINKHOLE_IP}"
    DOMAIN_COUNT=$((DOMAIN_COUNT + 1))
  done < "$BLOCKLIST"
  echo "$DOMAIN_COUNT" > "${TMPDIR:-/tmp}/.dns_filtering_count"
} > "$BLOCKLIST_CONF"
DOMAIN_COUNT="$(cat "${TMPDIR:-/tmp}/.dns_filtering_count")"
rm -f "${TMPDIR:-/tmp}/.dns_filtering_count"
printf '               (%s domains)\n' "$DOMAIN_COUNT"

# ---------------------------------------------------------------------------
# 3b. Render the logging / loopback-binding config
#     (upstream forwarding itself lives in the shipped meddefense-upstream.conf)
# ---------------------------------------------------------------------------
cat > "$LOGGING_CONF" << EOF
# Generated by 13-dns_filtering.sh -- do not edit by hand.
listen-address=127.0.0.1
bind-interfaces
log-queries
log-facility=${LOG_FILE}
EOF
touch "$LOG_FILE"

# Validate the rendered configuration before restarting the live service.
if ! dnsmasq --test --conf-file=/dev/null --conf-dir=/etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new >/tmp/dnsmasq_test.log 2>&1; then
  cat /tmp/dnsmasq_test.log >&2
  die "dnsmasq rejected the rendered configuration; see above"
fi

# ---------------------------------------------------------------------------
# 4. Restart dnsmasq and verify it is active
# ---------------------------------------------------------------------------
echo -n "[*] Restarting dnsmasq.service..."
systemctl restart dnsmasq 2>/tmp/dnsmasq_restart.log
sleep 1
STATUS="$(systemctl is-active dnsmasq 2>/dev/null)"
printf '        %s\n' "$STATUS"
if [[ "$STATUS" != "active" ]]; then
  cat /tmp/dnsmasq_restart.log >&2
  die "dnsmasq is not active after restart; check: journalctl -u dnsmasq"
fi

# ---------------------------------------------------------------------------
# 5. Validation queries
# ---------------------------------------------------------------------------
echo "[*] Validation queries..."

ALLOW_DOMAIN="$(grep -vE '^\s*(#|$)' "$ALLOWLIST" | head -1 | tr -d '[:space:]')"
BLOCK_DOMAIN="$(grep -vE '^\s*(#|$)' "$BLOCKLIST" | head -1 | tr -d '[:space:]')"

[[ -n "$ALLOW_DOMAIN" ]] || die "allowlist has no usable entries: $ALLOWLIST"
[[ -n "$BLOCK_DOMAIN" ]] || die "blocklist has no usable entries: $BLOCKLIST"

OVERALL_PASS=0

check_query() {
  local domain="$1" expected_label="$2" mode="$3"  # mode: allow | sinkhole
  local answer
  answer="$(dig +short +time=3 +tries=2 @127.0.0.1 "$domain" A 2>/dev/null | head -1)"

  local result="PASS"
  case "$mode" in
    sinkhole)
      [[ "$answer" == "$SINKHOLE_IP" ]] || result="FAIL"
      ;;
    allow)
      [[ -n "$answer" && "$answer" != "$SINKHOLE_IP" ]] || result="FAIL"
      ;;
  esac

  printf '  dig @127.0.0.1 %s\n' "$domain"
  printf '      -> %-24s expected %-9s %s\n' "${answer:-<no answer>}" "$expected_label" "$result"

  [[ "$result" == "PASS" ]] || OVERALL_PASS=1
}

check_query "$ALLOW_DOMAIN" "allow" "allow"
check_query "$BLOCK_DOMAIN" "sinkhole" "sinkhole"
check_query "$UNLISTED_DOMAIN" "allow" "allow"

exit "$OVERALL_PASS"